### ISSUE TITLE
Astrometry JSON files not being created for some datasets

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1361]
_Issue [HLA-767](https://jira.stsci.edu/browse/HLA-767) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Hunter reported in his testing that he found the astrometry quality assessment JSON files were not generated (dataset: jclnb5010 - jclnb5nfq) as reported on 28 April in Slack channel team-violet.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Hunter Brown](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hbrown) on [JIRA](https://jira.stsci.edu/browse/HLA-767?focusedCommentId=587204#comment-587204):_

As of HSTDP-2022.2.0-22~22c74910 I am still not observing jclnb5nfq_cal_qa_astrometry_resids.json being created.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Hunter Brown](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hbrown) on [JIRA](https://jira.stsci.edu/browse/HLA-767?focusedCommentId=587212#comment-587212):_

Logs in: /ifs/archive/test/hst/store/test/hunter/shared/HLA-767

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-767?focusedCommentId=587338#comment-587338):_

This is an association of two images which are filled with cosmic rays
though there is interesting nebulousity in a small portion of the frame.
The newer processing (HSTDP-2022.2) FAILED aposteriori alignment where
the older processing (2021.3.1) managed to succeed.

In the newer code, once the logic is transferred to tweakwcs for alignment
in quality_analysis.py, it is determined there are not enough cross-matched
sources between the image catalog and the reference catalog.

Since there were not enough matches, there was not a successful alignment.
Under these circumstances, no output will be generated for the 
astrometric analysis.

**Comment by nden** [comment]
The Jira ticket was resolved. Closing

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-767?focusedCommentId=587338#comment-587338):_

This is an association of two images which are filled with cosmic rays
 though there is interesting nebulousity in a small portion of the frame.
 The newer processing (HSTDP-2022.2) FAILED aposteriori alignment where
 the older processing (2021.3.1) managed to succeed.

In the newer code, once the logic is transferred to tweakwcs for alignment
 in quality_analysis.py, it is determined there are not enough cross-matched
 sources between the image catalog and the reference catalog.

Since there were not enough matches, there was not a successful alignment.
 Under these circumstances, no output will be generated for the 
 astrometric analysis.

This assessment indicates there was no problem with the JSON output generation code.  It will need to be assessed whether or not the association should have succeed with image alignment.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Hunter Brown](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hbrown) on [JIRA](https://jira.stsci.edu/browse/HLA-767?focusedCommentId=587204#comment-587204):_

As of HSTDP-2022.2.0-22~22c74910 I am still not observing jclnb5nfq_cal_qa_astrometry_resids.json being created.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-767?focusedCommentId=587338#comment-587338):_

This is an association of two images which are filled with cosmic rays
 though there is interesting nebulousity in a small portion of the frame.
 The newer processing (HSTDP-2022.2) FAILED aposteriori alignment where
 the older processing (2021.3.1) managed to succeed.

In the newer code, once the logic is transferred to tweakwcs for alignment
 in quality_analysis.py, it is determined there are not enough cross-matched
 sources between the image catalog and the reference catalog.

Since there were not enough matches, there was not a successful alignment.
 Under these circumstances, no output will be generated for the 
 astrometric analysis.

This assessment indicates there was no problem with the JSON output generation code.  It will need to be assessed whether or not the association should have succeed with image alignment.
