### ISSUE TITLE
MVM: Assignment of data to skycells

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1388]
_Issue [HLA-786](https://jira.stsci.edu/browse/HLA-786) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Matt thinks this issue may have already been addressed, but I am creating this ticket to ensure the problem is really resolved.

On 26 May 2022, Rick reported in team-burgundy slack channel that the X distribution of skycells is suspicious in that there are no skycells with x=1, very few with x=2 or x=20.  Further neither x=21 or y=21 has any skycells assigned as well.  Please see the slack channel discussion for a thorough description of the issue.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=592151#comment-592151):_

The same code gets used for computing both the X and Y positions within the projection cell, so that eliminates at least one obvious reason for the difference between the 2 histograms.  Additional testing will need to be performed with the code used to divide the projection cells into skycells in order to figure out what kind of issue in the code these histograms are showing.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623182#comment-623182):_

Just a report that this problem still exists. I re-ran it just now to look at the X and Y skycell positions for the current CAOM HAP-MVM products. The distribution has twice as many skycell layers as it had last May (53,746 versus 26,738, including only the "fine" skycells), but the distribution looks practically identical.

The first plot below shows the histograms of the X and Y values. They are expected to be uniform between 1 and 20. The Y distribution (bottom) is indeed nearly uniform, but the X distribution (top) is missing almost all skycells with X = 1, 2 or 20.

The second plot shows a grayscale image version of the counts, with the expected 1-20 boundary marked. The missing X columns are apparent.
!plot_mvm_cells2-2023jan03.png|height=400! 
!plot_mvm_cells4-2023jan03.png|height=400!

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623253#comment-623253):_

Thank you for confirming that this is still a problem.  Would it be possible to provide the IDs for skycells with X=2 or X=20?  Alternatively, would you provide a way for me to use the portal or HST-specific mast.stsci.edu interface to find skycells with these X values?  Finding data in such skycells would allow me to debug what is going on, as my analysis of the code thus far has not uncovered any explanations since the same code is used to identify the X and Y indices.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623584#comment-623584):_

Here's an example of a missing X=2 MVM image.  This SVM image overlaps the corners of 4 MVM skycells in projcell 2583:
```
hst_15350_09_wfc3_uvis_f673n_idlx09
```
There are MVM products for `p2583` `x03y06`, `x02y05`, and `x03y05`.  But the product for `p2583x02y06` is missing.  

Here's another example SVM image that is missing an X=2 MVM image:
```
hst_14644_17_acs_wfc_f814w_jd5h17
``` 
It has an MVM product in `hst_skycell-p1629x03y11_acs_wfc_f814w_all` but is missing the neighboring skycell `p1629x02y11`.  

Maybe a clue is that both of these do have data from neighboring projection cells.  E.g. the second case has an image `hst_skycell-p1630x19y11_acs_wfc_f814w_all` that covers approximately the same area that would be covered by `p1629x02y11`.  Possibly the problem is in the overlap regions between projection cells, where a single image should lead to skycell products generated from both projection cells.

Note that in the second case there should also be a `p1630x20y11` image, which is also missing.  This is an example of missing X=20 data. Again it is in the overlap with the adjacent projection cell.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623588#comment-623588):_

Here is a [MAST Portal link](https://mast.stsci.edu/portal/Mashup/Clients/Mast/Portal.html?searchQuery=%7B%22service%22%3A%22CAOMFILTERED%22%2C%22inputText%22%3A%5B%7B%22paramName%22%3A%22obs_collection%22%2C%22niceName%22%3A%22obs_collection%22%2C%22values%22%3A%5B%22HST%22%5D%2C%22valString%22%3A%22HST%22%2C%22isDate%22%3Afalse%2C%22separator%22%3A%22%3B%22%2C%22facetType%22%3A%22discrete%22%2C%22displayString%22%3A%22HST%22%7D%2C%7B%22paramName%22%3A%22provenance_name%22%2C%22niceName%22%3A%22provenance_name%22%2C%22values%22%3A%5B%5D%2C%22valString%22%3A%22HAP*%22%2C%22isDate%22%3Afalse%2C%22freeText%22%3A%22HAP%25%22%2C%22displayString%22%3A%22HAP*%22%7D%2C%7B%22paramName%22%3A%22filters%22%2C%22niceName%22%3A%22filters%22%2C%22values%22%3A%5B%5D%2C%22valString%22%3A%22f814w%22%2C%22isDate%22%3Afalse%2C%22separator%22%3A%22%3B%22%2C%22freeText%22%3A%22f814w%22%2C%22displayString%22%3A%22f814w%22%7D%5D%2C%22position%22%3A%22161.6020833333%2C%2014.02423888889%2C%200.2%22%2C%22paramsService%22%3A%22Mast.Caom.Filtered.Position%22%2C%22title%22%3A%22MAST%3A%20%20Advanced%20Search%203%22%2C%22tooltip%22%3A%22HST%3B%20HAP*%3B%20f814w%3B%20%20161.6020833333%2014.02423888889%3B%22%2C%22ra%22%3A161.6020833333%2C%22dec%22%3A14.02423888889%2C%22radius%22%3A0.2%2C%22columns%22%3A%22*%22%2C%22columnsConfig%22%3A%22Mast.Caom.Cone%22%7D) that (if it works) uses the advanced search to select the HAP SVM and MVM products at the location of the second example image.  It returns 3 products: the SVM, the MVM from `p1629x03y11` and the MVM from `p1630x19y11`.  You can use the checkboxes to highlight different products in the sky viewer to see their footprints.  The footprint for `p1629x03y11` is chopped off where `p1629x02y11` should appear.

**Comment by nden** [comment]
The JIRA ticket was resolved. Closing

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=592151#comment-592151):_

The same code gets used for computing both the X and Y positions within the projection cell, so that eliminates at least one obvious reason for the difference between the 2 histograms.  Additional testing will need to be performed with the code used to divide the projection cells into skycells in order to figure out what kind of issue in the code these histograms are showing.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623182#comment-623182):_

Just a report that this problem still exists. I re-ran it just now to look at the X and Y skycell positions for the current CAOM HAP-MVM products. The distribution has twice as many skycell layers as it had last May (53,746 versus 26,738, including only the "fine" skycells), but the distribution looks practically identical.

The first plot below shows the histograms of the X and Y values. They are expected to be uniform between 1 and 20. The Y distribution (bottom) is indeed nearly uniform, but the X distribution (top) is missing almost all skycells with X = 1, 2 or 20.

The second plot shows a grayscale image version of the counts, with the expected 1-20 boundary marked. The missing X columns are apparent.
!plot_mvm_cells2-2023jan03.png|height=400! 
!plot_mvm_cells4-2023jan03.png|height=400!

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623253#comment-623253):_

Thank you for confirming that this is still a problem.  Would it be possible to provide the IDs for skycells with X=2 or X=20?  Alternatively, would you provide a way for me to use the portal or HST-specific mast.stsci.edu interface to find skycells with these X values?  Finding data in such skycells would allow me to debug what is going on, as my analysis of the code thus far has not uncovered any explanations since the same code is used to identify the X and Y indices.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623584#comment-623584):_

Here's an example of a missing X=2 MVM image.  This SVM image overlaps the corners of 4 MVM skycells in projcell 2583:
```
hst_15350_09_wfc3_uvis_f673n_idlx09
```
There are MVM products for `p2583` `x03y06`, `x02y05`, and `x03y05`.  But the product for `p2583x02y06` is missing.  

Here's another example SVM image that is missing an X=2 MVM image:
```
hst_14644_17_acs_wfc_f814w_jd5h17
``` 
It has an MVM product in `hst_skycell-p1629x03y11_acs_wfc_f814w_all` but is missing the neighboring skycell `p1629x02y11`.  

Maybe a clue is that both of these do have data from neighboring projection cells.  E.g. the second case has an image `hst_skycell-p1630x19y11_acs_wfc_f814w_all` that covers approximately the same area that would be covered by `p1629x02y11`.  Possibly the problem is in the overlap regions between projection cells, where a single image should lead to skycell products generated from both projection cells.

Note that in the second case there should also be a `p1630x20y11` image, which is also missing.  This is an example of missing X=20 data. Again it is in the overlap with the adjacent projection cell.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=627119#comment-627119):_

I found some exposures which should be included as part of multiple SkyCells in the overlap between 2 projection cells, yet they were only included as members of 1 projection cell.  This may be partly (fully?) responsible for the issues with a lack of X=1,2,20 and 21 SkyCells since it is dropping the exposures from an X=2 SkyCell.

Data from `j8fncm` are identified as members of `skycell-p0695x19y12`, yet they also overlap `skycell-p0694x02y12` as well, but are not members of the p0694 SkyCell.  Understanding this problem may help solve some or all these problems.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=627376#comment-627376):_

[Drizzlepac PR #&#x2060;1503](https://github.com/spacetelescope/drizzlepac/pull/1503) has been filed to make a change to the logic used to identify what ProjectionCells overlap a set of exposures.  The logic now explicitly looks in the neighboring cells (both -1 and +1) along the ring of ProjectionsCells at a given declination (declination band) for any overlap with the input exposures.  Doing so allows the code to now correctly recognize overlap with the full range of X values.  For the two cases reported by R. White, the new results are:

> `Exposure idlx09ebq_flc.fits from visit idlx09 overlapped SkyCells:`
> `{'skycell-p2583x02y05': SkyCell object: skycell-p2583x02y05, 'skycell-p2583x02y06': SkyCell object: skycell-p2583x02y06, 'skycell-p2583x03y05': SkyCell object: skycell-p2583x03y05, 'skycell-p2583x03y06': SkyCell object: skycell-p2583x03y06, 'skycell-p2584x19y05': SkyCell object: skycell-p2584x19y05, 'skycell-p2584x19y06': SkyCell object: skycell-p2584x19y06`}


> `Exposure jd5h17gmq_flc.fits from visit jd5h17 overlapped SkyCells:`
> `{'skycell-p1629x02y11': SkyCell object: skycell-p1629x02y11, 'skycell-p1629x03y11': SkyCell object: skycell-p1629x03y11, 'skycell-p1630x19y11': SkyCell object: skycell-p1630x19y11, 'skycell-p1630x20y11': SkyCell object: skycell-p1630x20y11`}

In addition, the changes were also tested on a field in the galactic center where X=2 cells were missing as well; namely, data from visit `j8fncm`.  I am still looking for cases where there should be X=1 or X=21 cells to verify the full range of this fix, but for now, it appears that this change in logic should allow ALL the overlapping SkyCells to be identified and created as output MVM products.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=628600#comment-628600):_

HLA-940 will be used to follow up on whether or not the fix in [Drizzlepac PR #&#x2060;1503](https://github.com/spacetelescope/drizzlepac/pull/1503) completely resolves this problem.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=592151#comment-592151):_

The same code gets used for computing both the X and Y positions within the projection cell, so that eliminates at least one obvious reason for the difference between the 2 histograms.  Additional testing will need to be performed with the code used to divide the projection cells into skycells in order to figure out what kind of issue in the code these histograms are showing.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623182#comment-623182):_

Just a report that this problem still exists. I re-ran it just now to look at the X and Y skycell positions for the current CAOM HAP-MVM products. The distribution has twice as many skycell layers as it had last May (53,746 versus 26,738, including only the "fine" skycells), but the distribution looks practically identical.

The first plot below shows the histograms of the X and Y values. They are expected to be uniform between 1 and 20. The Y distribution (bottom) is indeed nearly uniform, but the X distribution (top) is missing almost all skycells with X = 1, 2 or 20.

The second plot shows a grayscale image version of the counts, with the expected 1-20 boundary marked. The missing X columns are apparent.
!plot_mvm_cells2-2023jan03.png|height=400! 
!plot_mvm_cells4-2023jan03.png|height=400!

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623253#comment-623253):_

Thank you for confirming that this is still a problem.  Would it be possible to provide the IDs for skycells with X=2 or X=20?  Alternatively, would you provide a way for me to use the portal or HST-specific mast.stsci.edu interface to find skycells with these X values?  Finding data in such skycells would allow me to debug what is going on, as my analysis of the code thus far has not uncovered any explanations since the same code is used to identify the X and Y indices.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=623584#comment-623584):_

Here's an example of a missing X=2 MVM image.  This SVM image overlaps the corners of 4 MVM skycells in projcell 2583:
```
hst_15350_09_wfc3_uvis_f673n_idlx09
```
There are MVM products for `p2583` `x03y06`, `x02y05`, and `x03y05`.  But the product for `p2583x02y06` is missing.  

Here's another example SVM image that is missing an X=2 MVM image:
```
hst_14644_17_acs_wfc_f814w_jd5h17
``` 
It has an MVM product in `hst_skycell-p1629x03y11_acs_wfc_f814w_all` but is missing the neighboring skycell `p1629x02y11`.  

Maybe a clue is that both of these do have data from neighboring projection cells.  E.g. the second case has an image `hst_skycell-p1630x19y11_acs_wfc_f814w_all` that covers approximately the same area that would be covered by `p1629x02y11`.  Possibly the problem is in the overlap regions between projection cells, where a single image should lead to skycell products generated from both projection cells.

Note that in the second case there should also be a `p1630x20y11` image, which is also missing.  This is an example of missing X=20 data. Again it is in the overlap with the adjacent projection cell.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=627119#comment-627119):_

I found some exposures which should be included as part of multiple SkyCells in the overlap between 2 projection cells, yet they were only included as members of 1 projection cell.  This may be partly (fully?) responsible for the issues with a lack of X=1,2,20 and 21 SkyCells since it is dropping the exposures from an X=2 SkyCell.

Data from `j8fncm` are identified as members of `skycell-p0695x19y12`, yet they also overlap `skycell-p0694x02y12` as well, but are not members of the p0694 SkyCell.  Understanding this problem may help solve some or all these problems.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=627376#comment-627376):_

[Drizzlepac PR #&#x2060;1503](https://github.com/spacetelescope/drizzlepac/pull/1503) has been filed to make a change to the logic used to identify what ProjectionCells overlap a set of exposures.  The logic now explicitly looks in the neighboring cells (both -1 and +1) along the ring of ProjectionsCells at a given declination (declination band) for any overlap with the input exposures.  Doing so allows the code to now correctly recognize overlap with the full range of X values.  For the two cases reported by R. White, the new results are:

> `Exposure idlx09ebq_flc.fits from visit idlx09 overlapped SkyCells:`
> `{'skycell-p2583x02y05': SkyCell object: skycell-p2583x02y05, 'skycell-p2583x02y06': SkyCell object: skycell-p2583x02y06, 'skycell-p2583x03y05': SkyCell object: skycell-p2583x03y05, 'skycell-p2583x03y06': SkyCell object: skycell-p2583x03y06, 'skycell-p2584x19y05': SkyCell object: skycell-p2584x19y05, 'skycell-p2584x19y06': SkyCell object: skycell-p2584x19y06`}


> `Exposure jd5h17gmq_flc.fits from visit jd5h17 overlapped SkyCells:`
> `{'skycell-p1629x02y11': SkyCell object: skycell-p1629x02y11, 'skycell-p1629x03y11': SkyCell object: skycell-p1629x03y11, 'skycell-p1630x19y11': SkyCell object: skycell-p1630x19y11, 'skycell-p1630x20y11': SkyCell object: skycell-p1630x20y11`}

In addition, the changes were also tested on a field in the galactic center where X=2 cells were missing as well; namely, data from visit `j8fncm`.  I am still looking for cases where there should be X=1 or X=21 cells to verify the full range of this fix, but for now, it appears that this change in logic should allow ALL the overlapping SkyCells to be identified and created as output MVM products.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-786?focusedCommentId=628600#comment-628600):_

HLA-940 will be used to follow up on whether or not the fix in [Drizzlepac PR #&#x2060;1503](https://github.com/spacetelescope/drizzlepac/pull/1503) completely resolves this problem.
